[default]
project_name = "Paper Trading"
description = "基于Python的证券市场模拟交易后台服务器."
version = "2.0.1"
api_prefix = "/api"
base_url = "@format http://{env[DYNACONF_PT_HOST]}:{env[DYNACONF_PT_PORT]}/"
allowed_origins = ["*"]
quotes_api_timeout = 2
quotes_max_retry = 3

    # 数据库相关配置
    [default.db]
    url = "@format mongodb://{env[DYNACONF_MONGO_USER]}:{env[DYNACONF_MONGO_PASSWORD]}@{env[DYNACONF_MONGO_HOST]}:{env[DYNACONF_MONGO_PORT]}"
    max_connections = 50
    min_connections = 10

    # Redis
    [default.redis]
    port = 6379
    hq_db = 15                      # 行情
    user_db = 9                     # 用户
    position_db = 8                 # 持仓

    # 数据库表名
    [default.db.collections]
    user = "users"
    user_assets_record = "user_assets_records"
    order = "orders"
    position = "position"
    statement = "statement"
    dividend_records = "dividend_records"

    # 日志
    [default.log]
    level = 10                      # 10 = DEBUG
    active = true

    # 服务
    [default.service]
    event_log = "e_log"
    event_error = "e_error"
    persistence_mode = "realtime"   # 数据持久化模式
    market = "china_a"              # 市场


[development]
dynaconf_merge = true
    # 引擎
    [development.engine]
    persistence_mode = "manual"     # 数据持久化模式

[production]
dynaconf_merge = true
    # 日志
    [production.log]
    level = 20                      # 20 = INFO

[testing]
dynaconf_merge = true
    # 数据库相关配置
    [testing.db]
    name = "test_paper_trading"

    # Redis
    [testing.redis]
    host = "127.0.0.1"
    port = 6379
    hq_db = 15                      # 行情
    user_db = 7                     # 用户
    position_db = 7                 # 持仓
